### ISSUE TITLE
result is multiplied on succesfull requests

### ISSUE THREAD

**Issue by MarcelWee** [Useful-Software-Solutions-Ltd/resource-retryer#1] opened 2015-10-03 19:12 UTC
Hi,

Thanks for making this resource retryer! It seems to work very well.

Apart from the fact that the result of a succesfull request is twice as big as without the resource retryer.
It seems to be an issue in the succes function where the returnObject gets the results pushed into it a second time.

Best regards,
Marcel

**Comment by JayChase** [comment] 2015-10-08 01:46
Hi. It's good to hear the code is working for you. I think the increase in size will be because the actions on the result will have been replaced with wrapped actions as well. I'll close this issue of, but let me know if I've missed something.

**Comment by PaulVanSchayck** [comment] 2015-10-17 16:18
Hi. So this happens for us on resource calls with isArray set. 

The problem is that in the resulting array the number of results are multiplied by the number of elements in the original result. 

We can fix it by setting `var returnObject = [];` before this [line](https://github.com/Useful-Software-Solutions-Ltd/resource-retryer/blob/master/source/resourceRetryer.module.js#L94). At the start of the success() function. But I doubt this is correct.

**Comment by JayChase** [comment] 2015-10-18 02:45
Hi. I've recreated the problem from you description. I'll try to get some time to fix this this week.

**Comment by JayChase** [comment] 2015-10-21 03:06
It looks like I've got this fixed now (v1.0.4). I am checking before pushing items on to the return object whether they have already been added or not. Thanks for your help spotting this. Let me know if the fix is working for you,

**Comment by MarcelWee** [comment] 2015-10-24 09:39
Hi Jay,

The fix is working nice! Thanks a lot for the effort!

**Comment by JayChase** [comment] 2015-10-29 00:17
No problem, thanks for the free testing.

**Closed as completed by JayChase** 2015-10-29 00:17 UTC
